


import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import TextContainer from "../components/containers/TextConatiner/TextContainer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} bg-primary`}>
        <div>
          <h1
            style={{ fontFamily: "'Carter One', cursive" }}
            className="text-white text-center"
          >
           Speed typing
          </h1>
        </div>
        <div className="">
          <div className="container-fluid">
            <TextContainer
            />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
